### ISSUE TITLE
uuid/v4 issue with enzyme

### ISSUE THREAD

**Issue by ryanve** [kelektiv/node-uuid#210] opened 2017-07-11 21:03 UTC
This is a heads up about https://github.com/airbnb/enzyme/issues/1020. Is it possible that uuid/v4 is not exported in a way that can be handled by all loaders?

It seems like modern tooling should handle `import uuidv4 from 'uuid/v4'` as it is in [`enzyme@2.9.1`](https://github.com/airbnb/enzyme/blob/v2.9.1/src/Utils.js#L5) but that failed [for us](https://github.com/plangrid/enzyme/pull/3) whereas `import { v4 as uuidv4 } from 'uuid'` works. Any idea why?

**Comment by broofa** [comment] 2017-07-11 21:22
Might this be due to [Enzyme depending on webpack@1.13.3](https://github.com/airbnb/enzyme/blob/master/package.json#L108)?  That's two major releases back from `latest`.  :-/

I have a project that does `import uuidv4 from 'uuid/v4'` using webpack@3.0.0 and it's working as expected.

**Comment by jadengore** [comment] 2017-08-01 21:03
@ryanve I have the same problem in my Webpack 2 project.

**Comment by ljharb** [comment] 2017-08-01 22:54
@broofa enzyme uses webpack in development, for karma, and does not use it whatsoever in its build process or as part of the published package - so that should be irrelevant.

**Comment by broofa** [comment] 2017-08-02 12:39
@ljharb So how is enzyme building the published package?

BTW, the reason `require('uuid').v4` works is because (for now) `uuid` still hangs the `v1` and `v4` properties off the `exports`.  But that's a legacy API that will go away in the next major release (whenever that happens).

FWIW, I see this as a packager issue and am not currently inclined to fix this.  The reason being that  the `uuid/v4` style provides better dependency isolation.  The legacy API resulted in the code for all uuid versions being bundled with the package regardless of what was used.   With the new style, projects should only get the code they needed for the specific version.

**Comment by ljharb** [comment] 2017-08-02 17:45
@broofa just with babel-cli. webpack is for apps to bundle things for the web; it makes no sense to webpack a published package.

(enzyme *is* using the `uuid/v4` syntax, which is strictly better)

**Comment by broofa** [comment] 2017-09-07 23:21
@ljharb: Where are we at with this?

From where I sit, the initial report seems related to old webpack versions.  But I think you're saying this is not webpack-related... but I don't know where to go with this.  I guess I need a detailed recipe to reproduce but, honestly, I have limited time to dig into this.  It'd be helpful if you or one of the other folks in this thread could pin this down to a specific problem in enzyme or how we're doing requires in this module.   Barring that, I'm afraid I'm going to have to close this out as unactionable.

**Comment by ljharb** [comment] 2017-09-08 00:18
@ryanve do you still have this problem?

**Comment by ryanve** [comment] 2017-09-08 01:13
@ljharb We resolved it by directly saving `uuid` alongside enzyme. [I haven't retried since.](https://github.com/airbnb/enzyme/issues/1020#issuecomment-314568137)

```
npm install uuid@^3.1 --save-dev
```

**Comment by broofa** [comment] 2017-09-11 16:02
Closing.  'Happy to reopen if/when someone finds an actionable issue here.

**Closed by broofa** 2017-09-11 16:02 UTC
