### ISSUE TITLE
IE11 on windows7 error: window.onerror · Function expected

### ISSUE THREAD

**Issue by topwebtek7** [kelektiv/node-uuid#273] opened 2018-04-17 19:16 UTC
![image](https://user-images.githubusercontent.com/16714648/38891234-44babe46-42b6-11e8-8f3c-e24d27c77ff6.png)

In our production app, we are getting this error for all IE11 users on Windows 7.
Any thoughts with this error?

**Comment by broofa** [comment] 2018-04-17 19:45
Duplicate of #265

**Closed by broofa** 2018-04-17 19:45 UTC
